bookapp/api/urls.py
from django.urls import path
from . import views

app_name = 'bookapp'

urlpatterns = [
    path('bookapi/',
         views.BookListView.as_view(),
         name='bookapi'),
]

bookapp/urls.py
from django.urls import path
from . import views

app_name = 'bookapp'

urlpatterns = [
    path('book_list',
         views.book_list,
         name='book_list'),
    path('newBook',
         views.add_new_book,
         name='add_new_book'),
    path('',
         views.main_page,
         name='mainPage'),
    path('<title>/<author>/<isbn_number>/<int:page_count>/',
         views.edit_book,
         name='edit_book'),
    path('book_search',
         views.book_search,
         name='book_search'),
    path('book_search_by_title',
         views.book_search_by_title,
         name='book_search_by_title'),
    path('test_json',
         views.test_json,
         name='test_json'),
    path('json_error',
         views.test_json,
         name='json_error'),
    path('<author>/<isbn_number>/<int:page_count>/',
         views.delete_book,
         name='delete_book'),
    path('book_search_by_date',
         views.book_search_by_date,
         name='book_search_by_date')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookapp/', include('bookapp.urls', namespace='bookapp')),
    path('api/', include('bookapp.api.urls', namespace='api')),
]

bookapp/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    isbnNumber = models.CharField(max_length=100)
    pageCount = models.IntegerField()
    imageLinks = models.TextField()
    language = models.TextField()
    published = models.DateField(auto_now=False)
    object = models.Manager()

    def get_absolute_url(self):
        return reverse('bookapp:edit_book',
                       args=[self.title,
                             self.author,
                             self.isbnNumber,
                             self.pageCount])

    def delete_book(self):
        return reverse('bookapp:delete_book',
                       args=[self.author,
                             self.isbnNumber,
                             self.pageCount])

    def __str__(self):
        return self.title

bookapp/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'isbnNumber', 'pageCount', 'imageLinks', 'language', 'published')


class SearchForm(forms.Form):
    query = forms.CharField()


class SearchBookByDataForm(forms.Form):
    od = forms.DateField()
    do = forms.DateField()


class AddBookForm(forms.Form):
    add = forms.URLField()

bookapp/api/views.py
from rest_framework import generics
from ..models import Book
from .serializers import BookSerializer


class BookListView(generics.ListAPIView):
    serializer_class = BookSerializer

    def get_queryset(self):
        qs = Book.object.all()
        title = self.request.GET.get("title")
        if title is not None:
            qs = qs.filter(title__contains=title)
        author = self.request.GET.get('author')
        if author is not None:
            qs = qs.filter(author__contains=author)
        return qs


class BookDetailView(generics.RetrieveAPIView):
    queryset = Book.object.all()
    serializer_class = BookSerializer

bookapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book
from .forms import BookForm, SearchForm, AddBookForm, SearchBookByDataForm
import requests
from json.decoder import JSONDecodeError


def main_page(request):
    return render(request,
                  'book/mainPage.html')


def book_search(request):
    return render(request,
                  'book/book_search.html')


def book_list(request):
    object_list = Book.object.all()
    return render(request,
                  'book/booklist.html',
                  {'books': object_list})


def add_new_book(request):
    value = False
    if request.method == 'POST':
        book_form = BookForm(data=request.POST)
        if book_form.is_valid():
            new_book = book_form.save(commit=False)
            new_book.save()
            value = True
    else:
        book_form = BookForm()

    return render(request,
                  'book/newBook.html',
                  {'book_form': book_form,
                   'value': value})


def edit_book(request, title, author, isbn_number, page_count):
    value = False
    book = get_object_or_404(Book,
                             title=title,
                             author=author,
                             isbnNumber=isbn_number,
                             pageCount=page_count)
    edit_form = BookForm(instance=book)
    if request.method == 'POST':
        book_form = BookForm(data=request.POST)
        if book_form.is_valid():
            book = book_form.save(commit=False)
            book.save()
            book = get_object_or_404(Book,
                                     title=title,
                                     author=author,
                                     isbnNumber=isbn_number,
                                     pageCount=page_count)
            book.delete()
            value = True
    return render(request,
                  'book/edit_book.html',
                  {'book': book,
                   'edit_form': edit_form,
                   'value': value})


def book_search_by_title(request):
    form = SearchForm()
    query = None
    results_by_title = []
    results_by_author = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results_by_title = Book.object.filter(title__contains=query)
            results_by_author = Book.object.filter(author__contains=query)
    return render(request,
                  'book/book_search_by_title.html',
                  {'form': form,
                   'query': query,
                   'results_by_title': results_by_title,
                   'results_by_author': results_by_author, })


def book_search_by_date(request):
    form = SearchBookByDataForm
    results_by_date = []
    if 'od' and 'do' in request.GET:
        form = SearchBookByDataForm(request.GET)
        if form.is_valid():
            od = form.cleaned_data['od']
            do = form.cleaned_data['do']
            results_by_date = Book.object.filter(published__range=[od, do])
    return render(request,
                  'book/book_search_by_date.html',
                  {'form': form,
                   'results_by_date': results_by_date})


def test_json(request):
    form = AddBookForm()
    value = False
    if 'add' in request.GET:
        form = AddBookForm(request.GET)
        if form.is_valid():
            try:
                add = form.cleaned_data['add']
                response = requests.get(add)
                data = response.json()
                title = data['items'][0]['volumeInfo']['title']
                author = data['items'][0]['volumeInfo']['authors'][0]
                isbn = data['items'][0]['volumeInfo']['industryIdentifiers'][0]['identifier']
                isbn = isbn[:8]
                page_count = data['items'][0]['volumeInfo']['pageCount']
                language = data['items'][0]['volumeInfo']['language']
                publish_date = data['items'][0]['volumeInfo']['publishedDate']
                if len(publish_date) == 7:
                    publish_date = publish_date + '-01'
                if len(publish_date) == 4:
                    publish_date = publish_date + '-01-01'
                image_links = data['items'][0]['volumeInfo']['canonicalVolumeLink']
                new_book = Book(title=title, author=author, isbnNumber=isbn, pageCount=page_count,
                                imageLinks=image_links, language=language, published=publish_date)
                new_book.save()
                value = True
                return render(request, 'book/json.html', {
                    'form': form,
                    'value': value,
                })
            except KeyError:
                return render(request, 'book/json_error.html', {
                })
            except JSONDecodeError:
                return render(request, 'book/json_error.html', {
                })
    return render(request, 'book/json.html', {
        'form': form,
        'value': value
    })


def delete_book(request, author, isbn_number, page_count):
    book = get_object_or_404(Book,
                             author=author,
                             isbnNumber=isbn_number,
                             pageCount=page_count)
    value = False
    if request.method == "POST":
        book.delete()
        value = True
        return render(request,
                      'book/book_delete.html',
                      {'value': value})
    return render(request,
                  'book/book_delete.html',
                  {'book': book,
                   'value': value})

bookapp/templates/book/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/book.css' %}" rel="stylesheet">
    </head>

    <body>
        <div id="header">
            <span class="logo">BookApp</span>
            <ul class="menu">
                <li>
                    <a href="{% url 'bookapp:book_list' %}">Lista książek</a>
                </li>
                <li>
                    <a href="{% url 'bookapp:add_new_book' %}">Dodaj nową książkę</a>
                </li>
                <li>
                    <a href="{% url 'bookapp:book_search' %}">Szukaj książki</a>
                </li>
                 <li>
                    <a href="{% url 'bookapp:test_json' %}">Dodaj książkę z API</a>
                </li>
            </ul>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

bookapp/templates/book/book_delete.html
{% extends "book/base.html" %}

{% block title %}Usuń{% endblock %}

{% block content %}
    {% if value %}
        <p>Książka została usunięta</p>
        <a href="{% url 'bookapp:book_list' %}">Wróć do zbioru książek</a>
    {% else %}
        <h1>Usuń książkę ze zbioru"</h1>
        <p>Czy na pewno chesz usunąć książke {{ book.title }}</p>
        <form action="" method="post">
            {% csrf_token %}
            <p><input type="submit" value="Tak usuń"></p>
        </form>
    {% endif %}
{% endblock %}

bookapp/templates/book/book_search.html
{% extends "book/base.html" %}

{% block title %}Szukaj ksiązki{% endblock %}

{% block content %}

<h1>Szukaj książki</h1>
<p><a href="{% url 'bookapp:book_search_by_title' %}">Szukaj po tytule lub autorze</a></p>
<p><a href="{% url 'bookapp:book_search_by_date' %}">Szukaj po dacie wydanie</a></p>
{% endblock %}

bookapp/templates/book/book_search_by_date.html
{% extends "book/base.html" %}

{% block title %}Szukaj ksiązki{% endblock %}

{% block content %}
<style>
#book_table {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#book_table td, #book_table th {
  border: 1px solid #ddd;
  padding: 8px;
}

#book_table tr:nth-child(even){background-color: #f2f2f2;}

#book_table tr:hover {background-color: #ddd;}

#book_table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #12c064;
  color: white;
}
</style>
<h1>Szukaj książki po dacie wydania</h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Szukaj">
    </form>
<table id="book_table">
   <tr>
      <th>Tytuł</th> <th>Autor</th><th>Numer ISBN</th><th>Liczba stron</th><th>Data wydania</th><th>Link</th><th>Język</th><th>Edycja</th>
   </tr>
{% for book in results_by_date %}
    <tr>
        <td>{{ book.title}}</td> <td>{{ book.author }}</td><td>{{ book.isbnNumber }}</td><td>{{ book.pageCount }}</td>
        <td>{{ book.published }}</td><td><a href="{{ book.imageLinks }}">Link do okładki</a> </td>
        <td>{{ book.language }}</td><td><a href="{{ book.get_absolute_url }}">Edytuj</a> </td>
    </tr>
{% endfor %}
</table>
{% endblock %}

bookapp/templates/book/book_search_by_title.html
{% extends "book/base.html" %}

{% block title %}Szukaj ksiązki{% endblock %}

{% block content %}
<style>
#book_table {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#book_table td, #book_table th {
  border: 1px solid #ddd;
  padding: 8px;
}

#book_table tr:nth-child(even){background-color: #f2f2f2;}

#book_table tr:hover {background-color: #ddd;}

#book_table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #12c064;
  color: white;
}
</style>
<h1>Szukaj po tytule lub autorze</h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Szukaj">
    </form>
<table id="book_table">
   <tr>
      <th>Tytuł</th> <th>Autor</th><th>Numer ISBN</th><th>Liczba stron</th><th>Link</th><th>Język</th><th>Edycja</th>
   </tr>

{% for book in results_by_title %}
<tr>
    <td>{{ book.title}}</td> <td>{{ book.author }}</td><td>{{ book.isbnNumber }}</td><td>{{ book.pageCount }}</td><td>{{ book.imageLinks }}</td>
    <td>{{ book.language }}</td><td><a href="{{ book.get_absolute_url }}">Edytuj</a> </td>
</tr>
{% endfor %}
{% for book in results_by_author %}
<tr>
    <td>{{ book.title}}</td> <td>{{ book.author }}</td><td>{{ book.isbnNumber }}</td><td>{{ book.pageCount }}</td><td>{{ book.imageLinks }}</td>
    <td>{{ book.language }}</td><td><a href="{{ book.get_absolute_url }}">Edytuj</a> </td>
</tr>
{% endfor %}
</table>
{% endblock %}

bookapp/templates/book/booklist.html
{% extends "book/base.html" %}

{% block title %}Lista książke{% endblock %}

{% block content %}
<style>
#book_table {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#book_table td, #book_table th {
  border: 1px solid #ddd;
  padding: 8px;
}

#book_table tr:nth-child(even){background-color: #f2f2f2;}

#book_table tr:hover {background-color: #ddd;}

#book_table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #12c064;
  color: white;
}
</style>
<h1>Lista kiążek</h1>
<table id="book_table">
   <tr>
      <th>Tytuł</th> <th>Autor</th><th>Numer ISBN</th><th>Liczba stron</th><th>Data wydania</th><th>Link</th><th>Język</th><th>Edycja</th>
   </tr>

{% for book in books %}
<tr>
    <td>{{ book.title}}</td> <td>{{ book.author }}</td><td>{{ book.isbnNumber }}</td><td>{{ book.pageCount }}</td>
    <td>{{ book.published }}</td><td><a href="{{ book.imageLinks }}">Link do okładki</a> </td>
    <td>{{ book.language }}</td><td><a href="{{ book.get_absolute_url }}">Edytuj</a> </td>
</tr>
{% endfor %}
</table>
{% endblock %}

bookapp/templates/book/edit_book.html
{% extends "book/base.html" %}

{% block title %}Edycja ksiązki{% endblock %}

{% block content %}
    <h1>Edycja książki "{{ book.title }}"</h1>
    {% if value %}
        <p>Dane zostały zmienione</p>
        <p><a href="{% url 'bookapp:book_list' %}">Wróć do zbioru książek</a></p>
    {% else %}
        <p>Dane ksiażki możesz zmienić przy pomocy poniższego formularza</p>
        <form action="" method="post">
            {{ edit_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Zapisz zmiany"></p>
            <a href="{{ book.delete_book }}">Usuń</a>
        </form>
    {% endif %}
{% endblock %}

bookapp/templates/book/json.html
{% extends "book/base.html" %}

{% block title %}Dodaj książkę{% endblock %}

{% block content %}

<h1>Dodaj ksiązkię z API Google</h1>
    {% if value %}
    <p>Książka została dodana do zbioru</p>
    {% else %}
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Dodaj">
    </form>
    {% endif %}
{% endblock %}

bookapp/templates/book/json_error.html
{% extends "book/base.html" %}

{% block title %}Błąd{% endblock %}

{% block content %}
<h1>Coś poszło nie tak</h1>
<p>Podany link był błędny</p>
{% endblock %}

bookapp/templates/book/mainPage.html
{% extends "book/base.html" %}

{% block title %}Strona główna{% endblock %}

{% block content %}
<h1>Strona główna</h1>
<p>Witaj na stronie BookApp</p>
{% endblock %}

bookapp/templates/book/newBook.html
{% extends "book/base.html" %}

{% block title %}Nowa książka{% endblock %}

{% block content %}

    {% if value %}
        <h2>Książka została dodana</h2>
        <a href="{% url 'bookapp:book_list' %}">Wróć do zbioru książek</a>
    {% else %}
        <h2>Dodaj nową książkę</h2>
        <form action="" method="post">
            {{ book_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Dodaj książkę"></p>
        </form>
    {% endif %}
    <a href="{% url 'bookapp:book_list' %}">Wróć do zbioru książek</a>
{% endblock %}